sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: yarn install
before_script:
  - npm prune
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test-compat
  - yarn test:coverage
  - yarn build:umd
after_success:
  - yarn report-coverage
branches:
  only: master
